@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTc1MzUyNTM2NTE3OSwicm9sZSI6ImFkbWluIiwiZW1haWwiOiJtaWRvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzUzNTM1OTk1LCJleHAiOjE3NTM1NDMxOTV9.oyFw-WJrLQL-DEkS_cZV7o5WHWaEG7ix92ILlSdc9pQ 

### 
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "mido@example.com",
  "password": "123456"
}


###
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "mido",
  "email": "mido@example.com",
  "role": "admin",
  "password": "123456"
}

### 🛍️ Get All Products
GET http://localhost:3000/products

###

### ➕ Add Product with All Fields
POST http://localhost:3000/products
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Wireless Mouse",
  "price": 25.5,
  "category": "Accessories",
  "description": "Ergonomic wireless mouse with silent clicks and 2.4GHz USB receiver.",
  "brand": "LogiTech",
  "stock": 45,
  "image": [
    "https://www.pexels.com/photo/close-up-photo-of-gaming-mouse-2115256/"
  ],
  "rating": 4.3,
  "reviews": 17,
  "tags": ["wireless", "mouse", "ergonomic", "usb"],
  "discount": 10,
  "isFeatured": false
}


###

### ✏️ Update Product
PUT http://localhost:3000/products/1753536015587
Content-Type: application/json
Authorization: {{token}}

{
  "price": 99.99,
  "category": "Electronics",
    "image": [
    "https://www.pexels.com/photo/close-up-photo-of-gaming-mouse-2115256/"
  ]
}

###

### 🗑️ Delete Product
DELETE http://localhost:3000/products/102
Authorization: {{token}}

###

### 🧾 Request Product Deletion (User)
POST http://localhost:3000/products/1753536015587/request-delete
Authorization: {{token}}

###

### 👥 Get All Users (no passwords shown)
GET http://localhost:3000/users
Authorization: {{token}}

### 📋 Get All Products Requested for Deletion
GET http://localhost:3000/products/requested-deletion
Authorization: {{token}}


### 🧾 Checkout Cart
POST http://localhost:3000/cart/checkout
Content-Type: application/json
Authorization: {{token}}

{
  "items": [
    { "productId": 1753536015587, "quantity": 100 }
  ]
}

###

### 📦 View My Orders
GET http://localhost:3000/orders/1753525365179
Authorization: {{token}}
